import type { Metadata } from "next";
import "./globals.css";
import { Header } from '@/components/Header';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="de">
            <body className="bg-background text-text" >
                <Header />
                <main className="max-w-4xl mx-auto w-full px-4 py-6">
                    {children}
                </main>
            </body>
        </html>
    );
}
